'use client';

import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { malaysiaInput, malaysiaISO, type LocalizedText, type ManagedPackage, type SiteConfig } from '@/lib/site-config';
import { field, glassPanel, secondaryButton } from './admin-ui';

export type EditorSection = 'Pricing & Offers' | 'Packages' | 'Guides' | 'Content' | 'Site Settings';
const blank = (): LocalizedText => ({ en: '', zh: '' });
const uid = () => crypto.randomUUID();

export function EditorPanel({ title, description, children, actions }: { title: string; description?: string; children: ReactNode; actions?: ReactNode }) {
  return <section className={`${glassPanel} min-w-0 p-5 sm:p-7`}>
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-lg font-semibold tracking-tight">{title}</h3>{description && <p className="mt-2! max-w-2xl text-sm leading-6 text-white/55">{description}</p>}</div>{actions}</div>
    <div className="grid gap-5">{children}</div>
  </section>;
}
export function TextField({ label, value, onChange, multiline = false, type = 'text', hint }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean; type?: string; hint?: string }) {
  return <label className="block min-w-0"><span className="mb-2 block text-xs font-medium text-white/75">{label}</span>{multiline ? <textarea value={value} onChange={e => onChange(e.target.value)} rows={3} className={`${field} resize-y leading-6`} /> : <input type={type} value={value} onChange={e => onChange(e.target.value)} className={field} />}{hint && <span className="mt-2 block text-xs leading-5 text-white/45">{hint}</span>}</label>;
}
export function Bilingual({ label, value, onChange, multiline = false }: { label: string; value: LocalizedText; onChange: (v: LocalizedText) => void; multiline?: boolean }) {
  return <fieldset className="min-w-0"><legend className="mb-3 text-sm font-medium text-white/85">{label}</legend><div className="grid gap-3 md:grid-cols-2"><TextField label={`${label} · English`} value={value.en} onChange={en => onChange({ ...value, en })} multiline={multiline} /><TextField label={`${label} · 中文`} value={value.zh} onChange={zh => onChange({ ...value, zh })} multiline={multiline} /></div></fieldset>;
}
export function Switch({ label, value, onChange, hint }: { label: string; value: boolean; onChange: (v: boolean) => void; hint?: string }) {
  return <label className="flex min-h-11 cursor-pointer items-start gap-3 rounded-lg border border-white/10 bg-white/[0.025] p-3"><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} className="mt-0.5 h-4 w-4 shrink-0 accent-cyan-300" /><span><span className="block text-sm text-white/85">{label}</span>{hint && <span className="mt-1 block text-xs leading-5 text-white/45">{hint}</span>}</span></label>;
}
function MoneyField({ label, value, onChange, optional = false }: { label: string; value: number | null; onChange: (v: number | null) => void; optional?: boolean }) {
  const hintId = useId();
  const [input, setInput] = useState(value === null ? '' : (value / 100).toFixed(2));
  const focused = useRef(false);
  useEffect(() => { if (!focused.current) setInput(value === null ? '' : Number.isFinite(value) ? (value / 100).toFixed(2) : ''); }, [value]);
  return <label className="block"><span className="mb-2 block text-xs font-medium text-white/75">{label} (RM)</span><input aria-label={`${label} (RM)`} aria-describedby={hintId} className={`${field} font-mono tabular-nums`} type="text" inputMode="decimal" pattern="[0-9]+(\.[0-9]{0,2})?" required={!optional} value={input} onFocus={() => { focused.current = true; }} onBlur={() => { focused.current = false; }} onChange={e => { const v = e.target.value; setInput(v); onChange(!v && optional ? null : /^\d+(\.\d{0,2})?$/.test(v) ? Math.round(Number(v) * 100) : NaN); }} /><span id={hintId} className="mt-2 block text-xs text-white/45">{optional ? 'Leave blank to remove the promotional price.' : 'MYR, up to two decimal places.'}</span></label>;
}
function OrderField({ value, onChange }: { value: number; onChange: (v: number) => void }) {
  return <label className="block"><span className="mb-2 block text-xs text-white/75">Display order</span><input type="number" min={0} max={100} step={1} className={field} value={value} onChange={e => onChange(Number(e.target.value))} /><span className="mt-2 block text-xs text-white/45">Lower numbers appear first.</span></label>;
}
const smallButton = `${secondaryButton} text-xs`;

export function SiteConfigEditor({ section, config, onChange, upload, uploading }: { section: EditorSection; config: SiteConfig; onChange: (v: SiteConfig) => void; upload: (file: File, kind: 'guide' | 'release', apply: (asset: { assetId: string; src?: string }) => void) => void; uploading: boolean }) {
  const replacePackage = (id: string, patch: Partial<ManagedPackage>) => onChange({ ...config, packages: config.packages.map(p => p.id === id ? { ...p, ...patch } : p) });
  const settings = (patch: Partial<SiteConfig['settings']>) => onChange({ ...config, settings: { ...config.settings, ...patch } });
  const content = (patch: Partial<SiteConfig['content']>) => onChange({ ...config, content: { ...config.content, ...patch } });
  if (section === 'Pricing & Offers') return <div className="grid gap-6">
    <EditorPanel title="Offer schedule" description="Promotional prices apply only within this window. All dates use Malaysia time (UTC+08:00); the end time is exclusive.">
      <div className="grid gap-3 sm:grid-cols-2"><Switch label="Enable promotional offer" value={config.offer.enabled} onChange={enabled => onChange({ ...config, offer: { ...config.offer, enabled } })} /><Switch label="Show offer countdown" value={config.offer.showCountdown} onChange={showCountdown => onChange({ ...config, offer: { ...config.offer, showCountdown } })} /></div>
      <div className="grid gap-4 sm:grid-cols-2">{(['startsAt', 'endsAt'] as const).map(key => <TextField key={key} label={key === 'startsAt' ? 'Starts · Malaysia time' : 'Ends · Malaysia time'} type="datetime-local" value={malaysiaInput(config.offer[key])} onChange={value => { if (value) onChange({ ...config, offer: { ...config.offer, [key]: malaysiaISO(value) } }); }} />)}</div>
    </EditorPanel>
    {config.packages.map(p => <EditorPanel key={p.id} title={p.name.en} description={p.id.replaceAll('_', ' ')}><div className="grid gap-4 sm:grid-cols-2"><MoneyField label="Regular price" value={p.amount} onChange={amount => replacePackage(p.id, { amount: amount ?? 0 })} /><MoneyField label="Promotional price" value={p.promotionalAmount} onChange={promotionalAmount => replacePackage(p.id, { promotionalAmount })} optional /></div><Switch label="Use promotional price during the offer" value={p.promotionEnabled} onChange={promotionEnabled => replacePackage(p.id, { promotionEnabled })} hint="Set a promotional price equal to or below the regular price." /></EditorPanel>)}
  </div>;
  if (section === 'Packages') return <div className="grid gap-6">{config.packages.map(p => <EditorPanel key={p.id} title={p.name.en} description={`Package ID: ${p.id}`}>
    <div className="grid gap-3 sm:grid-cols-3"><Switch label="Visible on website" value={p.visible} onChange={visible => replacePackage(p.id, { visible })} /><Switch label="Purchasing enabled" value={p.enabled} onChange={enabled => replacePackage(p.id, { enabled })} /><OrderField value={p.order} onChange={order => replacePackage(p.id, { order })} /></div>
    <Bilingual label="Package name" value={p.name} onChange={name => replacePackage(p.id, { name })} /><Bilingual label="Description" value={p.description} onChange={description => replacePackage(p.id, { description })} multiline /><Bilingual label="Badge" value={p.badge} onChange={badge => replacePackage(p.id, { badge })} />
    <div className="border-t border-white/10 pt-5"><div className="mb-4 flex items-center justify-between"><h4 className="text-sm font-medium">Package features</h4><button type="button" disabled={p.features.length >= 20} className={smallButton} onClick={() => replacePackage(p.id, { features: [...p.features, blank()] })}>Add feature</button></div><div className="grid gap-5">{p.features.map((feature, i) => <div key={i} className="grid gap-2"><Bilingual label={`Feature ${i + 1}`} value={feature} onChange={value => replacePackage(p.id, { features: p.features.map((v, index) => index === i ? value : v) })} /><button type="button" className="justify-self-end text-xs text-rose-200 underline underline-offset-4" onClick={() => replacePackage(p.id, { features: p.features.filter((_, index) => index !== i) })}>Remove feature {i + 1}</button></div>)}</div></div>
  </EditorPanel>)}</div>;
  if (section === 'Guides') return <div className="grid gap-6"><div className="flex flex-wrap items-center justify-between gap-4"><p className="max-w-xl text-sm leading-6 text-white/55">Upload a PNG, JPEG or WebP image. Uploaded assets become public when the saved draft is published.</p><label className={`${secondaryButton} cursor-pointer focus-within:outline-2 focus-within:outline-cyan-200 ${config.guides.length >= 30 || uploading ? 'pointer-events-none opacity-40' : ''}`}>Add guide<input type="file" aria-label="Add guide image" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={config.guides.length >= 30 || uploading} onChange={e => { const file = e.target.files?.[0]; if (file) upload(file, 'guide', asset => { if (asset.src) onChange({ ...config, guides: [...config.guides, { id: uid(), src: asset.src, title: blank(), description: blank(), alt: blank(), label: '', visible: false, order: config.guides.length }] }); }); e.target.value = ''; }} /></label></div>
    {config.guides.length === 0 && <EditorPanel title="No guides yet" description="Add a guide, upload its image, and write its captions before making it visible."><span className="text-xs text-white/40">Up to 30 guides</span></EditorPanel>}
    {config.guides.map((g, i) => { const update = (patch: Partial<typeof g>) => onChange({ ...config, guides: config.guides.map(v => v.id === g.id ? { ...v, ...patch } : v) }); return <EditorPanel key={g.id} title={g.title.en || `Guide ${i + 1}`} actions={<button type="button" className={smallButton} onClick={() => onChange({ ...config, guides: config.guides.filter(v => v.id !== g.id) })}>Remove guide</button>}>
      <div className="grid items-start gap-5 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div className="min-w-0"><img src={g.src} alt={g.alt.en || 'Guide image preview'} className="max-h-64 w-full rounded-lg border border-white/10 bg-black object-contain" /><p className="mt-2! break-all font-mono text-[10px] text-white/45">{g.src}</p></div><div className="grid gap-4"><label className="block text-xs text-white/75">Replace guide image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} className="mt-3 block w-full text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-3 file:text-white" onChange={e => { const file = e.target.files?.[0]; if (file) upload(file, 'guide', asset => { if (asset.src) update({ src: asset.src }); }); e.target.value = ''; }} /></label><Switch label="Visible on website" value={g.visible} onChange={visible => update({ visible })} /><OrderField value={g.order} onChange={order => update({ order })} /><TextField label="Guide label" value={g.label} onChange={label => update({ label })} /></div></div>
      <Bilingual label="Guide title" value={g.title} onChange={title => update({ title })} /><Bilingual label="Guide description" value={g.description} onChange={description => update({ description })} multiline /><Bilingual label="Image alternative text" value={g.alt} onChange={alt => update({ alt })} />
    </EditorPanel>; })}
  </div>;
  if (section === 'Content') return <div className="grid gap-6">
    <EditorPanel title="Hero copy" description="Edit the first screen of the storefront in both languages.">{(Object.keys(config.hero) as (keyof SiteConfig['hero'])[]).map(key => <Bilingual key={key} label={({ eyebrow: 'Eyebrow', line1: 'Headline line 1', line2: 'Headline line 2', description: 'Hero description', note: 'Hero note', primaryButton: 'Primary button', secondaryButton: 'Secondary button' })[key]} value={config.hero[key]} onChange={value => onChange({ ...config, hero: { ...config.hero, [key]: value } })} multiline={key === 'description'} />)}</EditorPanel>
    <EditorPanel title="Announcement"><Switch label="Show announcement" value={config.content.announcementEnabled} onChange={announcementEnabled => content({ announcementEnabled })} /><Bilingual label="Announcement text" value={config.content.announcement} onChange={announcement => content({ announcement })} multiline /></EditorPanel>
    <EditorPanel title="Website features" actions={<button type="button" className={smallButton} disabled={config.content.features.length >= 12} onClick={() => content({ features: [...config.content.features, { title: blank(), description: blank() }] })}>Add feature</button>}>
      {config.content.features.length === 0 && <p className="text-sm text-white/50">No additional website features.</p>}{config.content.features.map((feature, i) => <div key={i} className="grid gap-4 border-b border-white/10 pb-5 last:border-0"><Bilingual label={`Website feature ${i + 1} · Title`} value={feature.title} onChange={title => content({ features: config.content.features.map((v, index) => index === i ? { ...v, title } : v) })} /><Bilingual label={`Website feature ${i + 1} · Description`} value={feature.description} onChange={description => content({ features: config.content.features.map((v, index) => index === i ? { ...v, description } : v) })} multiline /><button type="button" className="justify-self-end text-xs text-rose-200 underline underline-offset-4" onClick={() => content({ features: config.content.features.filter((_, index) => index !== i) })}>Remove website feature {i + 1}</button></div>)}
    </EditorPanel>
    <EditorPanel title="Frequently asked questions" actions={<button type="button" className={smallButton} disabled={config.content.faqs.length >= 30} onClick={() => content({ faqs: [...config.content.faqs, { id: uid(), question: blank(), answer: blank(), visible: true }] })}>Add FAQ</button>}>
      {config.content.faqs.length === 0 && <p className="text-sm text-white/50">No FAQs yet.</p>}{config.content.faqs.map((faq, i) => { const update = (patch: Partial<typeof faq>) => content({ faqs: config.content.faqs.map(v => v.id === faq.id ? { ...v, ...patch } : v) }); return <div key={faq.id} className="grid gap-4 border-b border-white/10 pb-6 last:border-0"><Bilingual label={`FAQ ${i + 1} · Question`} value={faq.question} onChange={question => update({ question })} /><Bilingual label={`FAQ ${i + 1} · Answer`} value={faq.answer} onChange={answer => update({ answer })} multiline /><div className="flex flex-wrap items-center justify-between gap-3"><Switch label={`Show FAQ ${i + 1}`} value={faq.visible} onChange={visible => update({ visible })} /><button type="button" className={smallButton} onClick={() => content({ faqs: config.content.faqs.filter(v => v.id !== faq.id) })}>Remove FAQ {i + 1}</button></div></div>; })}
    </EditorPanel>
  </div>;
  return <div className="grid gap-6">
    <EditorPanel title="Availability" description="Maintenance and checkout switches are enforced when customers create orders."><div className="grid gap-3 sm:grid-cols-2"><Switch label="Maintenance mode" value={config.settings.maintenance} onChange={maintenance => settings({ maintenance })} /><Switch label="Enable checkout" value={config.settings.checkoutEnabled} onChange={checkoutEnabled => settings({ checkoutEnabled })} /></div><Bilingual label="Maintenance message" value={config.settings.maintenanceMessage} onChange={maintenanceMessage => settings({ maintenanceMessage })} multiline /><label className="block text-xs text-white/75">Default language<select value={config.settings.defaultLocale} onChange={e => settings({ defaultLocale: e.target.value === 'zh' ? 'zh' : 'en' })} className={`${field} mt-2`}><option value="en">English</option><option value="zh">中文</option></select></label></EditorPanel>
    <EditorPanel title="Contact and purchase information"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Support email" type="email" value={config.settings.supportEmail} onChange={supportEmail => settings({ supportEmail })} /><TextField label="Support URL" value={config.settings.supportUrl} onChange={supportUrl => settings({ supportUrl })} hint="A site path or an HTTPS URL." /></div><TextField label="Video URL" value={config.settings.videoUrl} onChange={videoUrl => settings({ videoUrl })} hint="HTTPS URL; leave blank to hide the video." /><Bilingual label="Purchase notice" value={config.content.purchaseNotice} onChange={purchaseNotice => content({ purchaseNotice })} multiline /></EditorPanel>
    <EditorPanel title="Extension release" description="Upload a ZIP release. Existing paid orders retain their original release; future orders use the published release."><label className="block text-xs text-white/75">Upload extension ZIP<input type="file" accept=".zip,application/zip" disabled={uploading} className="mt-3 block w-full text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-3 file:text-white" onChange={e => { const file = e.target.files?.[0]; if (file) upload(file, 'release', asset => settings({ extensionRelease: { assetId: asset.assetId, label: config.settings.extensionRelease?.label || file.name } })); e.target.value = ''; }} /></label>{config.settings.extensionRelease ? <><TextField label="Release label" value={config.settings.extensionRelease.label} onChange={label => settings({ extensionRelease: { ...config.settings.extensionRelease!, label } })} /><p className="break-all font-mono text-xs text-white/40">Asset: {config.settings.extensionRelease.assetId}</p><button type="button" className={`${smallButton} justify-self-start`} onClick={() => settings({ extensionRelease: null })}>Remove release from draft</button></> : <p className="text-sm text-white/50">No managed release selected.</p>}<p className="text-xs leading-5 text-cyan-200/80">Uploads are private. Save the draft and publish to apply this release.</p></EditorPanel>
  </div>;
}
