'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useLocale } from './LocaleProvider';
import { MessageList } from './TicketView';
import { getOrderPlanDisplay } from '@/lib/plans';
import { api,errorCopy } from '@/lib/client';
import { plans,price } from '@/lib/plans';
import type { Order,Ticket } from '@/lib/types';
type Data={orders:Order[];tickets:Ticket[]};
export function AdminDashboard(){
  const {locale,t}=useLocale();const [data,setData]=useState<Data|null>(null);const [auth,setAuth]=useState<boolean|null>(null);const [password,setPassword]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [tab,setTab]=useState<'orders'|'tickets'>('orders');const [search,setSearch]=useState('');const [selected,setSelected]=useState('');const [email,setEmail]=useState('');const [message,setMessage]=useState('');
  async function load(){try{setData(await api<Data>('/api/admin'));setAuth(true);}catch(e){if(e instanceof Error&&e.message==='UNAUTHORIZED'){setAuth(false);setData(null);}else setError(errorCopy(e,t));}}
  useEffect(()=>{void load();},[]);
  async function login(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await api('/api/admin/session',{method:'POST',body:JSON.stringify({password})});setPassword('');await load();}catch(e){setError(errorCopy(e,t));}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{await api('/api/admin/session',{method:'DELETE'});setData(null);setAuth(false);setSelected('');}catch(e){setError(errorCopy(e,t));}finally{setBusy(false);}}
  async function action(kind:string,id:string){setBusy(true);setError('');setNotice('');try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:kind,id,email,message})});setMessage('');await load();setNotice(kind==='resend'?t('交付预览已刷新。没有发送真实邮件。','Delivery preview refreshed. No actual email was sent.'):kind==='refund'?t('模拟订单已退款，交付预览已停用。','Simulated order refunded. Delivery preview disabled.'):t('已保存。','Saved.'));}catch(e){setError(errorCopy(e,t));}finally{setBusy(false);}}
  if(auth===false)return <div className="portal narrow"><Link className="back-link" href="/">← {t('回到网站','Back to website')}</Link><p className="eyebrow">VIBEFLOW / ADMIN</p><h1 className="portal-title">{t('管理员登录','Administrator sign-in')}</h1><p className="portal-intro">{t('查看本地测试订单、处理问题和管理交付预览。','Review local test orders, answer questions, and manage delivery previews.')}</p><div className="local-banner">{t('此后台仅限本机测试。使用 .env.local 中配置的本地管理员密码。','This dashboard is for local testing. Use the local admin password configured in .env.local.')}</div><form className="panel form" onSubmit={login}><label>{t('管理员密码','Admin password')}<input type="password" autoComplete="current-password" name="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?t('登录中…','Signing in…'):t('登录后台','Sign in')} ↗</button></form></div>;
  if(!data)return <div className="portal"><p className={error?'form-error':'loading-state'} role={error?'alert':undefined}>{error||t('加载管理后台…','Loading dashboard…')}</p></div>;
  const paid=data.orders.filter(o=>o.status==='paid');const q=search.toLowerCase().trim();const order=tab==='orders'?data.orders.find(o=>o.id===selected):undefined;const ticket=tab==='tickets'?data.tickets.find(o=>o.id===selected):undefined;
  return <div className="portal"><div className="admin-top"><div><p className="eyebrow">VIBEFLOW / LOCAL OPERATIONS</p><h1 className="portal-title">{t('管理后台','Your dashboard')}</h1></div><button className="button small" disabled={busy} onClick={logout}>{t('退出登录','Sign out')}</button></div><div className="local-banner">{t('本地模拟环境：所有金额、付款、通知密钥和交付预览均为测试数据。此处不会发送真实邮件或操作 HitPay。','Local simulation: all amounts, payments, notification keys, and deliveries are test data. No emails are sent and no HitPay transactions are performed.')}</div><div className="admin-stats"><div className="stat-card"><span>{t('全部订单','All orders')}</span><strong>{data.orders.length}</strong></div><div className="stat-card"><span>{t('模拟已付金额','Simulated paid total')}</span><strong>{price(paid.reduce((sum,o)=>sum+o.amount,0))}</strong></div><div className="stat-card"><span>{t('待回复工单','Open tickets')}</span><strong>{data.tickets.filter(x=>x.status==='open').length}</strong></div></div><div className="tabs" role="tablist" aria-label={t('后台页面','Dashboard views')}><button role="tab" aria-selected={tab==='orders'} className={tab==='orders'?'active':''} onClick={()=>{setTab('orders');setSelected('');setNotice('');}}>{t('订单','Orders')} ({data.orders.length})</button><button role="tab" aria-selected={tab==='tickets'} className={tab==='tickets'?'active':''} onClick={()=>{setTab('tickets');setSelected('');setNotice('');}}>{t('客服工单','Support tickets')} ({data.tickets.length})</button></div><div className="inline-actions" style={{marginTop:0,marginBottom:20}}><input className="inline-input" aria-label={t('搜索订单或工单','Search orders or tickets')} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('搜索邮箱、订单号或问题标题…','Search email, reference, or subject…')}/><button className="button small" onClick={load} disabled={busy}>{t('刷新','Refresh')}</button></div>
    {tab==='orders'?(data.orders.length?<div className="table-scroll"><table className="admin-table"><thead><tr><th>{t('订单号','Reference')}</th><th>{t('邮箱','Email')}</th><th>{t('方案','Package')}</th><th>{t('金额','Amount')}</th><th>{t('状态','Status')}</th><th>{t('操作','Action')}</th></tr></thead><tbody>{data.orders.filter(o=>`${o.reference} ${o.email}`.toLowerCase().includes(q)).map(o=><tr key={o.id}><td>{o.reference}</td><td>{o.email||'—'}</td><td>{getOrderPlanDisplay(o.plan,locale).name}</td><td>{price(o.amount)}</td><td><span className={`status-badge ${o.status}`}>{o.status}</span></td><td><button className="table-action" onClick={()=>{setSelected(o.id);setEmail(o.email);setNotice('');setError('');}}>{t('管理订单','Manage order')}</button></td></tr>)}</tbody></table></div>:<div className="empty-state">{t('还没有订单。先从首页测试购买流程。','No orders yet. Test a checkout from the website first.')}</div>):(data.tickets.length?<div className="table-scroll"><table className="admin-table"><thead><tr><th>{t('问题','Subject')}</th><th>{t('邮箱','Email')}</th><th>{t('订单号','Reference')}</th><th>{t('状态','Status')}</th><th>{t('操作','Action')}</th></tr></thead><tbody>{data.tickets.filter(o=>`${o.subject} ${o.email} ${o.reference}`.toLowerCase().includes(q)).map(o=><tr key={o.id}><td>{o.subject}</td><td>{o.email}</td><td>{o.reference||'—'}</td><td><span className={`status-badge ${o.status}`}>{o.status}</span></td><td><button className="table-action" onClick={()=>{setSelected(o.id);setMessage('');setNotice('');setError('');}}>{t('查看工单','View ticket')}</button></td></tr>)}</tbody></table></div>:<div className="empty-state">{t('还没有工单。客户提交的问题会显示在这里。','No support tickets yet. New customer questions will appear here.')}</div>)}
    {order&&<section className="panel admin-detail"><div className="admin-detail-head"><h2>{order.reference}</h2><button className="button small" onClick={()=>setSelected('')}>{t('关闭详情','Close details')} ×</button></div><div className="status-display"><div className="row"><span>{t('状态','Status')}</span><strong>{order.status}</strong></div><div className="row"><span>{t('方案','Package')}</span><strong>{getOrderPlanDisplay(order.plan,locale).name}</strong></div><div className="row"><span>{t('预览重发次数','Preview resends')}</span><strong>{order.resends}</strong></div></div>{order.status==='paid'&&<><label className="form" style={{marginTop:22,fontSize:12,gap:10}}>{t('修正接收邮箱','Correct delivery email')}<input className="inline-input" type="email" aria-label={t('修正接收邮箱','Correct delivery email')} value={email} onChange={e=>setEmail(e.target.value)}/></label><div className="inline-actions"><button className="button small primary" disabled={busy} onClick={()=>action('resend',order.id)}>{t('更新并重发预览','Update & resend preview')}</button><button className="button small danger" disabled={busy} onClick={()=>action('refund',order.id)}>{t('模拟退款','Simulate refund')}</button></div></>}<div className="inline-actions"><Link className="text-link" href={`/order/${order.token}`} target="_blank" rel="noopener noreferrer">{t('打开客户订单页','Open customer order')} ↗</Link></div></section>}
    {ticket&&<section className="panel admin-detail"><div className="admin-detail-head"><h2>{ticket.subject}</h2><button className="button small" onClick={()=>setSelected('')}>{t('关闭详情','Close details')} ×</button></div><div className="ticket-meta"><span>{ticket.email}</span><span>{ticket.reference}</span><span className={`status-badge ${ticket.status}`}>{ticket.status}</span></div><MessageList messages={ticket.messages}/>{ticket.status==='open'&&<form className="form" onSubmit={e=>{e.preventDefault();void action('reply',ticket.id);}}><label>{t('回复客户','Reply to customer')}<textarea name="reply" required minLength={1} maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="inline-actions"><button className="button primary" disabled={busy}>{t('保存回复','Save reply')} ↗</button><button type="button" className="button" disabled={busy} onClick={()=>action('close',ticket.id)}>{t('关闭工单','Close ticket')}</button></div></form>}<div className="inline-actions"><Link className="text-link" href={`/support/${ticket.token}`} target="_blank" rel="noopener noreferrer">{t('打开客户工单页','Open customer conversation')} ↗</Link></div></section>}{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}
  </div>;
}
