'use client';
import Image from 'next/image';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useLocale } from './LocaleProvider';
import { api,errorCopy } from '@/lib/client';
import { getOrderPlanDisplay,price } from '@/lib/plans';
import type { Order } from '@/lib/types';
import {beginAmbientNavigation} from '@/lib/ambientActivity';
export function Checkout({token}:{token:string}){
  const {locale,t}=useLocale();const router=useRouter();const [order,setOrder]=useState<Order|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [email,setEmail]=useState('');
  useEffect(()=>{api<Order>(`/api/orders/${token}`).then(setOrder).catch(e=>setError(errorCopy(e,t)));},[token]);
  async function action(kind:'complete'|'cancel',event?:React.FormEvent){event?.preventDefault();setBusy(true);setError('');try{await api(`/api/orders/${token}`,{method:'POST',body:JSON.stringify({action:kind,email})});beginAmbientNavigation();router.push(`/order/${token}`);}catch(e){setError(errorCopy(e,t));setBusy(false);}}
  if(!order)return <div className="portal narrow"><Link prefetch={true} className="back-link" href="/">← {t('回到网站','Back to website')}</Link>{error?<p role="alert" className="form-error">{error}</p>:<p className="loading-state">{t('正在加载订单…','Loading your order…')}</p>}</div>;
  const plan=getOrderPlanDisplay(order.plan,locale);return <div className="portal checkout-page"><div className="checkout-grid"><div className="checkout-copy"><Link prefetch={true} className="back-link" href="/#pricing">← {t('回到方案','Back to packages')}</Link><p className="eyebrow">VIBEFLOW CHECKOUT / LOCAL PREVIEW</p><h1 className="portal-title">{t('再一步，即可开始。','One step closer.')}</h1><p className="portal-intro">{t('确认方案和接收邮箱，然后测试付款与交付流程。','Confirm your package and delivery email, then test the checkout flow.')}</p><div className="local-banner">{t('本地模拟付款。不会扣款，不会发送邮件，也不会提供真实扩展或激活密钥。正式 HitPay 接入后，邮箱会在支付页面收集。','Local payment simulation. No money is collected, no email is sent, and no real extension or activation key is provided. Live HitPay checkout will collect the delivery email.')}</div></div><section className="panel checkout-panel" aria-label={t('付款信息','Payment details')}><div className="order-summary"><Image src="/files/logo.png" alt="" width="52" height="52" sizes="52px" quality={100}/><div><h2>{plan.name}</h2><p>{plan.period && `${plan.period} · `}{order.reference}</p></div></div><div className="order-total"><span>{t('合计 / MYR','Total / MYR')}</span><strong>{price(order.amount)}</strong></div>{order.status==='pending'?<form className="form" onSubmit={e=>action('complete',e)}><label>{t('接收邮箱','Delivery email')}<input aria-label={t('接收邮箱','Delivery email')} aria-describedby="checkout-email-help" type="email" name="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><small id="checkout-email-help">{t('用于测试交付预览和订单客服，不会发送真实邮件。','Used for local delivery previews and order support. No actual email is sent.')}</small></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?t('处理中…','Processing…'):t('模拟付款成功','Simulate successful payment')} <span aria-hidden>↗</span></button><button type="button" className="button secondary" onClick={()=>action('cancel')} disabled={busy}>{t('模拟取消付款','Simulate cancelled payment')}</button></form>:<><p className="notice">{t('此订单已处理。','This order has already been processed.')}</p><Link prefetch={true} className="button primary" href={`/order/${token}`}>{t('查看订单','View order')} ↗</Link></>}</section></div></div>;
}
