'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useLocale } from './LocaleProvider';
import { api,errorCopy } from '@/lib/client';
export function SupportForm(){const {locale,t}=useLocale();const [email,setEmail]=useState('');const [reference,setReference]=useState('');const [subject,setSubject]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const q=new URLSearchParams(window.location.search);setReference(q.get('reference')||'');setEmail(q.get('email')||'');},[]);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await api<{url:string}>('/api/support',{method:'POST',body:JSON.stringify({email,reference,subject,message,locale})});window.location.assign(response.url);}catch(e){setError(errorCopy(e,t));setBusy(false);}}
  return <section className="portal checkout-page support-page"><div className="checkout-grid"><div className="checkout-copy"><Link prefetch={true} className="back-link" href="/">← {t('回到网站','Back to website')}</Link><p className="eyebrow">VIBEFLOW SUPPORT</p><h1 className="portal-title">{t('有问题，我们来帮忙。','Let’s sort it out.')}</h1><p className="portal-intro">{t('安装、配置或订单遇到问题？把细节告诉我们。无需注册账号。','Installation, setup, or order questions? Tell us what happened. No account needed.')}</p><div className="local-banner">{t('本地客服测试：工单会保存在此电脑，可在管理后台回复。当前不会发送真实邮件。','Local support test: tickets are saved on this computer and can be answered from the admin dashboard. No actual email is sent.')}</div></div><form className="panel checkout-panel support-panel form" onSubmit={submit}><label>{t('邮箱地址','Email address')}<input name="email" type="email" autoComplete="email" maxLength={254} required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>{t('订单号（选填）','Order reference (optional)')}<input name="reference" maxLength={80} value={reference} onChange={e=>setReference(e.target.value)} placeholder="VF-…"/><small>{t('订单问题请填写订单号及付款邮箱；购买前咨询可留空。','For order help, use the reference and checkout email. Leave empty for pre-purchase questions.')}</small></label><label>{t('问题标题','Subject')}<input name="subject" minLength={2} maxLength={120} required value={subject} onChange={e=>setSubject(e.target.value)} placeholder={t('例如：Windows 插件安装问题','For example: Windows installation help')}/></label><label>{t('问题详情','Message')}<textarea name="message" rows={3} minLength={5} maxLength={4000} required value={message} onChange={e=>setMessage(e.target.value)} placeholder={t('描述你尝试的步骤和遇到的问题…','What did you try, and what happened?')}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?t('提交中…','Sending…'):t('创建工单','Create support ticket')} <span aria-hidden>↗</span></button><small>{t('提交后请保存专属工单链接，之后可通过链接查看回复。','After submitting, save your private ticket link to view replies.')}</small></form></div></section>;
}
