'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useLocale } from './LocaleProvider';
import { api,errorCopy } from '@/lib/client';
import type { Ticket,Message } from '@/lib/types';
export function MessageList({messages}:{messages:Message[]}){const {locale,t}=useLocale();return <div className="messages">{messages.map(m=><article key={m.id} className={`message ${m.author}`}><div className="message-head"><strong>{m.author==='admin'?'Vibeflow Support':t('你','You')}</strong><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString(locale==='zh'?'zh-CN':'en-MY',{timeZone:'Asia/Kuala_Lumpur'})} MYT</time></div><p className="message-body">{m.body}</p></article>)}</div>;}
export function TicketView({token}:{token:string}){
  const {t}=useLocale();const [ticket,setTicket]=useState<Ticket|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [copied,setCopied]=useState(false);
  async function refresh(){setBusy(true);setError('');try{setTicket(await api<Ticket>(`/api/support/${token}`));}catch(e){setError(errorCopy(e,t));}finally{setBusy(false);}}
  useEffect(()=>{void refresh();const timer=setInterval(()=>{api<Ticket>(`/api/support/${token}`).then(setTicket).catch(()=>{});},15000);return ()=>clearInterval(timer);},[token]);
  async function reply(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{setTicket(await api<Ticket>(`/api/support/${token}`,{method:'POST',body:JSON.stringify({message})}));setMessage('');}catch(e){setError(errorCopy(e,t));}finally{setBusy(false);}}
  async function copy(){try{await navigator.clipboard.writeText(window.location.href);setCopied(true);}catch{setError(t('请复制浏览器地址栏中的链接。','Please copy the link from your browser address bar.'));}}
  return <div className="portal narrow"><Link className="back-link" href="/support">← {t('客服中心','Support center')}</Link><p className="eyebrow">YOUR PRIVATE CONVERSATION</p><h1 className="portal-title">{ticket?.subject||t('工单详情','Your support ticket')}</h1><div className="local-banner">{t('请保存此专属链接。此本地版本不会发送邮件；管理员可在 /admin 回复，回复将在此显示。','Save this private link. This local version does not send email; admin replies from /admin will appear here.')}</div>{ticket&&<><div className="ticket-meta"><span className={`status-badge ${ticket.status}`}>{ticket.status}</span><span>{ticket.email}</span>{ticket.reference&&<span>{ticket.reference}</span>}</div><MessageList messages={ticket.messages}/>{ticket.status==='open'?<form className="form panel" onSubmit={reply}><label>{t('继续回复','Add a reply')}<textarea name="message" required minLength={1} maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="button primary" disabled={busy}>{t('发送回复','Send reply')} ↗</button></form>:<p className="notice">{t('此工单已关闭。如需进一步帮助，请创建新工单。','This ticket is closed. Open a new ticket if you need more help.')}</p>}<div className="portal-actions"><button className="button" onClick={copy}>{copied?t('已复制链接','Link copied'):t('保存工单链接','Copy ticket link')}</button><button className="button" disabled={busy} onClick={refresh}>{t('刷新回复','Refresh replies')}</button></div></>}{!ticket&&!error&&<p className="loading-state">{t('加载中…','Loading…')}</p>}{error&&<p className="form-error" role="alert">{error}</p>}</div>;
}
